/*RATES*/
export default {
  RATES: {
    'CAD': { symbol: '$' },
    'HKD': { symbol: '$' },
    'ISK': { symbol: 'kr' },
    'PHP': { symbol: '₱' },
    'DKK': { symbol: 'kr' },
    'HUF': { symbol: 'Ft' },
    'CZK': { symbol: 'Kč' },
    'GBP': { symbol: '£' },
    'RON': { symbol: 'lei' },
    'SEK': { symbol: 'kr' },
    'IDR': { symbol: 'Rp' },
    'INR': { symbol: '' },
    'BRL': { symbol: 'R$' },
    'RUB': { symbol: '₽' },
    'HRK': { symbol: 'kn' },
    'JPY': { symbol: '¥' },
    'THB': { symbol: '฿' },
    'CHF': { symbol: 'CHF' },
    'EUR': { symbol: '€' },
    'MYR': { symbol: 'RM' },
    'BGN': { symbol: 'лв' },
    'TRY': { symbol: '' },
    'CNY': { symbol: '¥' },
    'NOK': { symbol: 'kr' },
    'NZD': { symbol: '$' },
    'ZAR': { symbol: 'R' },
    'USD': { symbol: '$' },
    'MXN': { symbol: '$' },
    'SGD': { symbol: '$' },
    'AUD': { symbol: '$' },
    'ILS': { symbol: '₪' },
    'KRW': { symbol: '₩' },
    'PLN': { symbol: 'zł' }
  },
};

